"""Changed the user model to only store email as pii and allow for multiple oauth providers

Revision ID: 7786860af907
Revises: 14a9215363ca
Create Date: 2024-09-19 21:36:11.862623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7786860af907'
down_revision = '14a9215363ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('_oauth_provider_uc', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('name')
        batch_op.drop_column('oauth_provider')
        batch_op.drop_column('oauth_provider_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('oauth_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('_oauth_provider_uc', ['oauth_provider', 'oauth_provider_id'])

    op.drop_table('oauth_providers')
    # ### end Alembic commands ###
