"""Updated models to have better relationships and prepared User model for oauth integration

Revision ID: 7bf4313f8f0c
Revises: a1e981d6156f
Create Date: 2024-09-17 17:47:37.834052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf4313f8f0c'
down_revision = 'a1e981d6156f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('skills_skill_key', type_='unique')
        batch_op.create_unique_constraint('_user_skill_uc', ['user_id', 'skill'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_user_skill_uc', type_='unique')
        batch_op.create_unique_constraint('skills_skill_key', ['skill'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
