"""empty message

Revision ID: a1e981d6156f
Revises: dc7229af99f5
Create Date: 2024-09-17 17:12:22.557106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e981d6156f'
down_revision = 'dc7229af99f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=128), nullable=False),
    sa.Column('first_used_date', sa.Date(), nullable=True),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_skill',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('history_id', 'skill_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('career_history')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_history', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('history_skill')
    op.drop_table('history')
    op.drop_table('skills')
    # ### end Alembic commands ###
