import type { Metadata } from "next";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div className="grid grid-cols-[300px_1fr] min-h-screen gap-1">
      <nav className="bg-violet-500 text-white">
        <ul className="flex flex-col gap-6 mt-5">
          <li><Link className="block p-3 w-full h-full hover:bg-violet-600" href="/dashboard">Dashboard</Link></li>
          <li><Link className="block p-3 w-full h-full hover:bg-violet-600" href="/dashboard/skills">Skills list</Link></li>
          <li><Link className="block p-3 w-full h-full hover:bg-violet-600" href="/dashboard/history">Career history</Link></li>
          <li><Link className="block p-3 w-full h-full hover:bg-violet-600" href="/dashboard/settings">Settings</Link></li>
        </ul>
      </nav>
      <div className="flex flex-col p-6 pt-5">
        {children}
      </div>
    </div>
  );
}
